#!/bin/sh
ssh ubuntu@18.229.33.44 <<EOF
    cd ~/backNutriOlla
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    sudo npm install
    sudo npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF